@startuml mtc-refactory


archimate  "用户" as user <<business-actor>>

archimate  #LightBlue "车道业务" as bizLogic <<service>>
archimate  #grey  "黑名单服务" as blservice <<service>>
archimate  #pink  "计费服务" as biservice <<service>>
' archimate  #green  "交互界面" as blservice <<service>>

archimate #lightgreen "打印机"  as printer <<physical-equipment>>
archimate #red "栏杆"  as brake <<physical-facility>>
archimate #orange "读卡器"  as reader <<physical-material>>


bizLogic -down-> user : 交互
bizLogic -down-> printer : 控制
bizLogic -down-> reader : 控制
bizLogic -down-> brake : 控制
bizLogic -down-> blservice : 调用
bizLogic -down-> biservice : 调用

@enduml