@startuml mtc-cloud
rectangle 车道1 {
    archimate  "用户" as user1 <<business-actor>>
    archimate #lightgreen "打印机"  as printer1 <<physical-equipment>>
    archimate #red "栏杆"  as brake1 <<physical-facility>>
    archimate #orange "读卡器"  as reader1 <<physical-material>>
}

rectangle 车道2 {
    archimate  "用户" as user2 <<business-actor>>
    archimate #lightgreen "打印机"  as printer2 <<physical-equipment>>
    archimate #red "栏杆"  as brake2 <<physical-facility>>
    archimate #orange "读卡器"  as reader2 <<physical-material>>
}

cloud 云-数据中心节点 {
    archimate  #LightBlue "车道业务" as bizLogic <<business-collaboration>>

    archimate  #grey  "黑名单服务" as blservice <<service>>
    archimate  #pink  "计费服务" as biservice1 <<service>>
    archimate  #pink  "计费服务" as biservice2 <<service>>

}

cloud 车道1-工控机 {
    archimate  #red  "栏杆服务" as brakeservice1 <<service>>
    archimate  #orange  "读卡服务" as readerservice1 <<service>>
    archimate  #Yellow  "交互界面" as ui1 <<service>>
    archimate  #lightgreen  "打印服务" as printerservice1 <<service>>
}

cloud 车道2-工控机 {
    archimate  #red  "栏杆服务" as brakeservice2 <<service>>
    archimate  #orange  "读卡服务" as readerservice2 <<service>>
    archimate  #Yellow  "交互界面" as ui2 <<service>>
    archimate  #lightgreen  "打印服务" as printerservice2 <<service>>
}



bizLogic -down-> ui1 : 调用
ui1 <-down-> user1 : 交互

bizLogic -down-> printerservice1 : 调用
printerservice1 -down-> printer1 : 控制

bizLogic -down-> readerservice1 : 调用
readerservice1 -down-> reader1 :控制

bizLogic -down-> brakeservice1 : 调用
brakeservice1 -down-> brake1 : 控制


bizLogic -down-> blservice : 调用
bizLogic -down-> biservice2 : 调用


bizLogic -down-> ui2 : 调用
ui2 <-down-> user2 : 交互

bizLogic -down-> printerservice2 : 调用
printerservice2 -down-> printer2 : 控制

bizLogic -down-> readerservice2 : 调用
readerservice2 -down-> reader2 :控制

bizLogic -down-> brakeservice2 : 调用
brakeservice2 -down-> brake2 : 控制

bizLogic -down-> biservice1 : 调用

@enduml