@startuml mtc-model

[*] --> 车辆进入
车辆进入 -> 车辆被识别 : 确认车辆标识

车辆被识别 --> 车辆可通行 : 黑名单查询通过
车辆被识别 -down-> 车辆异常 : 黑名单查询未通过

车辆可通行 -> 行程获取 : 读卡成功

行程获取 -->  费用已计算 : 计费成功
费用已计算 ->  已收费 : 收费成功
已收费 -down->  已打发票 : 打印发票成功

已打发票 -down->  已放行 : 抬杆成功

已放行 -down-> 车辆驶出 : 驶出

车辆进入 -down-> 车辆异常 : 未能识别
车辆可通行 -down-> 车辆异常 : 读卡失败
行程获取 -down-> 车辆异常 : 计费失败
费用已计算 -down-> 车辆异常 : 收费失败
已收费 -down-> 车辆异常 : 打票失败
已打发票 -down-> 车辆异常 : 抬杆失败

车辆异常 --> [*] : 处理完成
车辆驶出 --> [*] : 完成


@enduml