@startuml
actor       车道前端      as uTolling
participant TollingService          as sTolling
queue       Queue                   as RabbitMQ
participant RecognizingService      as sRecognizing
actor       识别前端  as uRecognizing

uTolling -> sTolling : GET /register
uTolling -> sTolling : GET /tollings
uTolling -> sTolling : GET /start?id=xxxx
sTolling -> RabbitMQ : start(xxxx)
RabbitMQ -> sRecognizing : start(xxxx)
uRecognizing -> sRecognizing : GET /unconfirmed
uRecognizing -> sRecognizing : GET /confirm?id=(xxxx)
sRecognizing -> RabbitMQ : recognizing_successes(xxxx)
RabbitMQ -> sTolling : recognizing_successes(xxxx)
uTolling -> sTolling : GET /tollings

@enduml

